name: Garick Bay
favicon: null
layout_spectrum: 0.23314228793606162
typography_spectrum: 0.7231903395149857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#cbcbbe'
    - '#606b6f'
    - '#b28665'
    - '#1f2d36'
  brandStrength: 0.25
  lightness: 0.5828539114445448
  saturation: 0.6555891507305205
  rhythmicContrast: 0.2427467603702098
purpose: []
